#############################################################################
# Generated by PAGE version 4.3.1
# in conjunction with Tcl version 8.6
#    Sep 12, 2014 01:04:45 PM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top36
    namespace eval ::widgets::$base {
        set set,origin 1
        set set,size 1
        set runvisible 1
    }
    set site_3_0 $base.m44
    set site_4_0 $site_3_0.men45
    set site_4_0 $site_3_0.men45
    set site_3_0 $base.m44
    set site_4_0 $site_3_0.men49
    set site_4_0 .top36.tNo36.pg0 
    set site_4_0 $site_4_0
    set site_4_1 .top36.tNo36.pg1 
    set site_4_2 .top36.tNo36.pg2 
    set site_4_3 .top36.tNo36.pg3 
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow. {base} {
    if {$base == ""} {
        set base .
    }
    ###################
    # CREATING WIDGETS
    ###################
    wm focusmodel $top passive
    wm geometry $top 200x200+150+150; update
    wm maxsize $top 2564 1006
    wm minsize $top 116 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm withdraw $top
    wm title $top "page"
    bindtags $top "$top Page all"
    ###################
    # SETTING GEOMETRY
    ###################

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top36 {base} {
    if {$base == ""} {
        set base .top36
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl:toplevel $top -class Toplevel \
        -menu "$top.m44" -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 800x600+449+141; update
    wm maxsize $top 1920 1080
    wm minsize $top 800 600
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Stage7 Installer GUI"
    vTcl:DefineAlias "$top" "ToplevelRoot" vTcl:Toplevel:WidgetProc "" 1
    bindtags $top "$top Toplevel all _TopLevel"
    menu $top.m44 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    $top.m44 add cascade \
        -menu "$top.m44.men45" -activebackground {#d9d9d9} \
        -activeforeground {#111111} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label File 
    set site_3_0 $top.m44
    menu $site_3_0.men45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 0 
    $site_3_0.men45 add cascade \
        -menu "$site_3_0.men45.men46" -activebackground {#d9d9d9} \
        -activeforeground {#111111} -accelerator ctrl+i -background {#d9d9d9} \
        -font TkMenuFont -foreground {#000000} -label {Import profile} 
    set site_4_0 $site_3_0.men45
    menu $site_4_0.men46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 0 
    $site_3_0.men45 add cascade \
        -menu "$site_3_0.men45.men48" -activebackground {#d9d9d9} \
        -activeforeground {#111111} -accelerator ctrl+e -background {#d9d9d9} \
        -font TkMenuFont -foreground {#000000} -label {Export profile} 
    set site_4_0 $site_3_0.men45
    menu $site_4_0.men48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 0 
    $site_3_0.men45 add command \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -accelerator ctrl+c -background {#d9d9d9} -command exit() \
        -font TkMenuFont -foreground {#000000} -label Exit 
    $top.m44 add cascade \
        -menu "$top.m44.men49" -activebackground {#d9d9d9} \
        -activeforeground {#111111} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label Help 
    set site_3_0 $top.m44
    menu $site_3_0.men49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 0 
    $site_3_0.men49 add cascade \
        -menu "$site_3_0.men49.men50" -activebackground {#d9d9d9} \
        -activeforeground {#111111} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label About 
    set site_4_0 $site_3_0.men49
    menu $site_4_0.men50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 0 
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo36 \
        -width 794 -height 586 -takefocus {} 
    vTcl:DefineAlias "$top.tNo36" "TNotebook1" vTcl:WidgetProc "ToplevelRoot" 1
    frame .top36.tNo36.pg0 -background #d9d9d9
    $top.tNo36 add .top36.tNo36.pg0 \
        -padding 0 -sticky nsew -state normal -text Normal -image {} \
        -compound none -underline -1 
    set site_4_0  $top.tNo36.pg0
    ttk::entry $site_4_0.tEn38 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$site_4_0.tEn38" "TEntry1" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::label $site_4_0.tLa39 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text Hostname: 
    vTcl:DefineAlias "$site_4_0.tLa39" "TLabel1" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::label $site_4_0.tLa40 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Root password:} 
    vTcl:DefineAlias "$site_4_0.tLa40" "TLabel2" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::label $site_4_0.tLa41 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Add user:} 
    vTcl:DefineAlias "$site_4_0.tLa41" "TLabel3" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::progressbar $site_4_0.tPr42
    vTcl:DefineAlias "$site_4_0.tPr42" "TProgressbar1" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_4_0.tBu43 \
        -takefocus {} -text Build! 
    vTcl:DefineAlias "$site_4_0.tBu43" "TButton1" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::entry $site_4_0.tEn44 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$site_4_0.tEn44" "TEntry2" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::entry $site_4_0.tEn45 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$site_4_0.tEn45" "TEntry3" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::label $site_4_0.tLa46 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Stage3 tarball:} 
    vTcl:DefineAlias "$site_4_0.tLa46" "TLabel4" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::label $site_4_0.tLa47 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Time remaining:} 
    vTcl:DefineAlias "$site_4_0.tLa47" "TLabel5" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::label $site_4_0.tLa37 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Time elapsed:} 
    vTcl:DefineAlias "$site_4_0.tLa37" "TLabel6" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::label $site_4_0.tLa38 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Percentage complete:} 
    vTcl:DefineAlias "$site_4_0.tLa38" "TLabel7" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_4_0.tBu44 \
        -takefocus {} -text {Portage options} 
    vTcl:DefineAlias "$site_4_0.tBu44" "TButton2" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::entry $site_4_0.tEn46 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$site_4_0.tEn46" "TEntry4" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::combobox $site_4_0.tCo49 \
        -values {x86 AMD64} -textvariable combobox -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo49" "TCombobox1" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::label $site_4_0.tLa50 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {CPU architecture:} 
    vTcl:DefineAlias "$site_4_0.tLa50" "TLabel8" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::label $site_4_0.tLa51 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {System Settings} 
    vTcl:DefineAlias "$site_4_0.tLa51" "TLabel9" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::label $site_4_0.tLa52 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {User Settings} 
    vTcl:DefineAlias "$site_4_0.tLa52" "TLabel10" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::label $site_4_0.tLa53 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Number of CPU cores:} 
    vTcl:DefineAlias "$site_4_0.tLa53" "TLabel11" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::combobox $site_4_0.tCo54 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo54" "TCombobox2" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::label $site_4_0.tLa55 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Portage snapshot} 
    vTcl:DefineAlias "$site_4_0.tLa55" "TLabel12" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::label $site_4_0.tLa56 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text Bootloader 
    vTcl:DefineAlias "$site_4_0.tLa56" "TLabel13" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::label $site_4_0.tLa57 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Storage Settings} 
    vTcl:DefineAlias "$site_4_0.tLa57" "TLabel14" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::label $site_4_0.tLa58 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {User password:} 
    vTcl:DefineAlias "$site_4_0.tLa58" "TLabel15" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::entry $site_4_0.tEn59 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$site_4_0.tEn59" "TEntry5" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::label $site_4_0.tLa60 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Network Settings} 
    vTcl:DefineAlias "$site_4_0.tLa60" "TLabel16" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::label $site_4_0.tLa61 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Partition layout:} 
    vTcl:DefineAlias "$site_4_0.tLa61" "TLabel17" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::label $site_4_0.tLa62 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Partition formats:} 
    vTcl:DefineAlias "$site_4_0.tLa62" "TLabel18" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::label $site_4_0.tLa63 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Partitions to mount:} 
    vTcl:DefineAlias "$site_4_0.tLa63" "TLabel19" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::label $site_4_0.tLa64 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text Timezone: 
    vTcl:DefineAlias "$site_4_0.tLa64" "TLabel20" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::label $site_4_0.tLa65 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Kernel sources:} 
    vTcl:DefineAlias "$site_4_0.tLa65" "TLabel21" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::label $site_4_0.tLa66 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Add RC services:} 
    vTcl:DefineAlias "$site_4_0.tLa66" "TLabel22" vTcl:WidgetProc "ToplevelRoot" 1
    ttk::label $site_4_0.tLa67 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Delete RC services:} 
    vTcl:DefineAlias "$site_4_0.tLa67" "TLabel23" vTcl:WidgetProc "ToplevelRoot" 1
    place $site_4_0.tEn38 \
        -in $site_4_0 -x 100 -y 30 -width 146 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tLa39 \
        -in $site_4_0 -x 23 -y 30 -width 76 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tLa40 \
        -in $site_4_0 -x 0 -y 50 -anchor nw -bordermode ignore 
    place $site_4_0.tLa41 \
        -in $site_4_0 -x 30 -y 70 -anchor nw -bordermode ignore 
    place $site_4_0.tPr42 \
        -in $site_4_0 -x 10 -y 450 -width 770 -height 22 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tBu43 \
        -in $site_4_0 -x 680 -y 480 -width 96 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tEn44 \
        -in $site_4_0 -x 100 -y 50 -width 146 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tEn45 \
        -in $site_4_0 -x 100 -y 70 -width 146 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tLa46 \
        -in $site_4_0 -x 550 -y 30 -width 86 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tLa47 \
        -in $site_4_0 -x 10 -y 500 -width 91 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tLa37 \
        -in $site_4_0 -x 10 -y 480 -anchor nw -bordermode ignore 
    place $site_4_0.tLa38 \
        -in $site_4_0 -x 10 -y 520 -anchor nw -bordermode ignore 
    place $site_4_0.tBu44 \
        -in $site_4_0 -x 680 -y 410 -anchor nw -bordermode ignore 
    place $site_4_0.tEn46 \
        -in $site_4_0 -x 640 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.tCo49 \
        -in $site_4_0 -x 690 -y 60 -width 73 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tLa50 \
        -in $site_4_0 -x 580 -y 60 -anchor nw -bordermode ignore 
    place $site_4_0.tLa51 \
        -in $site_4_0 -x 610 -y 0 -anchor nw -bordermode ignore 
    place $site_4_0.tLa52 \
        -in $site_4_0 -x 78 -y 3 -width 71 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tLa53 \
        -in $site_4_0 -x 560 -y 90 -width 122 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tCo54 \
        -in $site_4_0 -x 691 -y 90 -width 43 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tLa55 \
        -in $site_4_0 -x 560 -y 120 -anchor nw -bordermode ignore 
    place $site_4_0.tLa56 \
        -in $site_4_0 -x 560 -y 140 -anchor nw -bordermode ignore 
    place $site_4_0.tLa57 \
        -in $site_4_0 -x 70 -y 160 -width 96 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tLa58 \
        -in $site_4_0 -x 10 -y 90 -anchor nw -bordermode ignore 
    place $site_4_0.tEn59 \
        -in $site_4_0 -x 100 -y 90 -width 146 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tLa60 \
        -in $site_4_0 -x 70 -y 270 -anchor nw -bordermode ignore 
    place $site_4_0.tLa61 \
        -in $site_4_0 -x 20 -y 190 -anchor nw -bordermode ignore 
    place $site_4_0.tLa62 \
        -in $site_4_0 -x 20 -y 210 -anchor nw -bordermode ignore 
    place $site_4_0.tLa63 \
        -in $site_4_0 -x 20 -y 230 -anchor nw -bordermode ignore 
    place $site_4_0.tLa64 \
        -in $site_4_0 -x 560 -y 160 -anchor nw -bordermode ignore 
    place $site_4_0.tLa65 \
        -in $site_4_0 -x 560 -y 190 -anchor nw -bordermode ignore 
    place $site_4_0.tLa66 \
        -in $site_4_0 -x 560 -y 220 -anchor nw -bordermode ignore 
    place $site_4_0.tLa67 \
        -in $site_4_0 -x 560 -y 250 -anchor nw -bordermode ignore 
    frame .top36.tNo36.pg1 -background #d9d9d9
    $top.tNo36 add .top36.tNo36.pg1 \
        -padding 0 -sticky nsew -state normal -text Chroot -image {} \
        -compound none -underline -1 
    set site_4_1  $top.tNo36.pg1
    frame .top36.tNo36.pg2 -background #d9d9d9
    $top.tNo36 add .top36.tNo36.pg2 \
        -padding 0 -sticky nsew -state normal -text Stage4 -image {} \
        -compound none -underline -1 
    set site_4_2  $top.tNo36.pg2
    frame .top36.tNo36.pg3 -background #d9d9d9
    $top.tNo36 add .top36.tNo36.pg3 \
        -padding 0 -sticky nsew -state normal -text Stage7 -image {} \
        -compound none -underline -1 
    set site_4_3  $top.tNo36.pg3
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo36 \
        -in $top -x 0 -y 0 -width 794 -height 586 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top36

