#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.3.1
# In conjunction with Tcl version 8.6
#    Oct 01, 2014 11:22:27 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import Installer_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.title('Stage7_Installer_GUI')
    root.geometry('800x600+404+62')
    Installer_support.set_Tk_var()
    w = Stage7_Installer_GUI (root)
    Installer_support.init(root, w)
    root.mainloop()

w = None
def create_Stage7_Installer_GUI (root, param=None):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    w.title('Stage7_Installer_GUI')
    w.geometry('800x600+404+62')
    Installer_support.set_Tk_var()
    w_win = Stage7_Installer_GUI (w)
    Installer_support.init(w, w_win, param)
    return w_win

def destroy_Stage7_Installer_GUI ():
    global w
    w.destroy()
    w = None


class Stage7_Installer_GUI:
    def __init__(self, master=None):
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])
        master.configure(background="#d9d9d9")
        master.configure(highlightbackground="#d9d9d9")
        master.configure(highlightcolor="black")


        self.menubar = Menu(master,bg=_bgcolor,fg=_fgcolor)
        master.configure(menu = self.menubar)

        self.file = Menu(master,tearoff=0)
        self.menubar.add_cascade(menu=self.file,
                activebackground="#d9d9d9",
                activeforeground="#111111",
                background="#d9d9d9",
                foreground="#000000",
                label="File")
        self.import_profile = Menu(master,tearoff=0)
        self.file.add_cascade(menu=self.import_profile,
                activebackground="#d9d9d9",
                activeforeground="#111111",
                accelerator="ctrl+i",
                background="#d9d9d9",
                foreground="#000000",
                label="Import profile")
        self.export_profile = Menu(master,tearoff=0)
        self.file.add_cascade(menu=self.export_profile,
                activebackground="#d9d9d9",
                activeforeground="#111111",
                accelerator="ctrl+e",
                background="#d9d9d9",
                foreground="#000000",
                label="Export profile")
        self.file.add_command(
                activebackground="#d9d9d9",
                activeforeground="#000000",
                accelerator="ctrl+c",
                background="#d9d9d9",
                command=Installer_support.exit(),
                foreground="#000000",
                label="Exit")
        self.help = Menu(master,tearoff=0)
        self.menubar.add_cascade(menu=self.help,
                activebackground="#d9d9d9",
                activeforeground="#111111",
                background="#d9d9d9",
                foreground="#000000",
                label="Help")
        self.about = Menu(master,tearoff=0)
        self.help.add_cascade(menu=self.about,
                activebackground="#d9d9d9",
                activeforeground="#111111",
                background="#d9d9d9",
                foreground="#000000",
                label="About")


        self.style.configure('TNotebook.Tab',background=_bgcolor)
        self.style.configure('TNotebook.Tab',foreground=_fgcolor)
        self.style.map('TNotebook.Tab',background=
            [('selected', _compcolor), ('active',_ana2color)])
        self.TNotebook1 = ttk.Notebook(master)
        self.TNotebook1.place(relx=0.0,rely=0.0,relheight=0.98,relwidth=0.99)
        self.TNotebook1.configure(width=794)
        self.TNotebook1.configure(takefocus="")
        self.TNotebook1_pg0 = ttk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_pg0, padding=3)
        self.TNotebook1.tab(0, text="Normal",underline="-1",)
        self.TNotebook1_pg1 = ttk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_pg1, padding=3)
        self.TNotebook1.tab(1, text="Chroot",underline="-1",)
        self.TNotebook1_pg2 = ttk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_pg2, padding=3)
        self.TNotebook1.tab(2, text="Stage4",underline="-1",)
        self.TNotebook1_pg3 = ttk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_pg3, padding=3)
        self.TNotebook1.tab(3, text="Stage7",underline="-1",)

        self.TProgressbar1 = ttk.Progressbar (self.TNotebook1_pg0)
        self.TProgressbar1.place(relx=0.01,rely=0.8,relheight=0.04
                ,relwidth=0.97)

        self.TButton1 = ttk.Button (self.TNotebook1_pg0)
        self.TButton1.place(relx=0.86,rely=0.86,height=35,width=96)
        self.TButton1.configure(takefocus="")
        self.TButton1.configure(text='''Build!''')

        self.TLabel5 = ttk.Label (self.TNotebook1_pg0)
        self.TLabel5.place(relx=0.01,rely=0.89,height=19,width=91)
        self.TLabel5.configure(background=_bgcolor)
        self.TLabel5.configure(foreground="#000000")
        self.TLabel5.configure(relief=FLAT)
        self.TLabel5.configure(text='''Time remaining:''')

        self.TLabel6 = ttk.Label (self.TNotebook1_pg0)
        self.TLabel6.place(relx=0.01,rely=0.86,height=19,width=77)
        self.TLabel6.configure(background=_bgcolor)
        self.TLabel6.configure(foreground="#000000")
        self.TLabel6.configure(relief=FLAT)
        self.TLabel6.configure(text='''Time elapsed:''')

        self.TLabel7 = ttk.Label (self.TNotebook1_pg0)
        self.TLabel7.place(relx=0.01,rely=0.93,height=19,width=119)
        self.TLabel7.configure(background=_bgcolor)
        self.TLabel7.configure(foreground="#000000")
        self.TLabel7.configure(relief=FLAT)
        self.TLabel7.configure(text='''Percentage complete:''')

        self.TButton2 = ttk.Button (self.TNotebook1_pg0)
        self.TButton2.place(relx=0.86,rely=0.73,height=25,width=94)
        self.TButton2.configure(takefocus="")
        self.TButton2.configure(text='''Portage options''')

        self.TLabelframe3 = ttk.Labelframe (self.TNotebook1_pg0)
        self.TLabelframe3.place(relx=0.01,rely=0.48,relheight=0.29
                ,relwidth=0.29)
        self.TLabelframe3.configure(text='''Network Settings''')
        self.TLabelframe3.configure(width=230)

        self.TLabelframe4 = ttk.Labelframe (self.TNotebook1_pg0)
        self.TLabelframe4.place(relx=0.01,rely=0.27,relheight=0.21
                ,relwidth=0.29)
        self.TLabelframe4.configure(text='''Partition Settings''')
        self.TLabelframe4.configure(width=230)

        self.TLabel17 = ttk.Label (self.TLabelframe4)
        self.TLabel17.place(relx=0.04,rely=0.32,height=19,width=88)
        self.TLabel17.configure(background=_bgcolor)
        self.TLabel17.configure(foreground="#000000")
        self.TLabel17.configure(relief=FLAT)
        self.TLabel17.configure(text='''Partition layout:''')

        self.TLabel18 = ttk.Label (self.TLabelframe4)
        self.TLabel18.place(relx=0.04,rely=0.5,height=19,width=96)
        self.TLabel18.configure(background=_bgcolor)
        self.TLabel18.configure(foreground="#000000")
        self.TLabel18.configure(relief=FLAT)
        self.TLabel18.configure(text='''Partition formats:''')

        self.TLabel19 = ttk.Label (self.TLabelframe4)
        self.TLabel19.place(relx=0.04,rely=0.67,height=19,width=110)
        self.TLabel19.configure(background=_bgcolor)
        self.TLabel19.configure(foreground="#000000")
        self.TLabel19.configure(relief=FLAT)
        self.TLabel19.configure(text='''Partitions to mount:''')

        self.TLabelframe5 = ttk.Labelframe (self.TNotebook1_pg0)
        self.TLabelframe5.place(relx=0.0,rely=0.02,relheight=0.24,relwidth=0.32)

        self.TLabelframe5.configure(text='''User Settings''')
        self.TLabelframe5.configure(width=250)

        self.TLabel2 = ttk.Label (self.TLabelframe5)
        self.TLabel2.place(relx=0.04,rely=0.35,height=19,width=85)
        self.TLabel2.configure(background=_bgcolor)
        self.TLabel2.configure(foreground="#000000")
        self.TLabel2.configure(relief=FLAT)
        self.TLabel2.configure(text='''Root password:''')

        self.TLabel3 = ttk.Label (self.TLabelframe5)
        self.TLabel3.place(relx=0.04,rely=0.5,height=19,width=54)
        self.TLabel3.configure(background=_bgcolor)
        self.TLabel3.configure(foreground="#000000")
        self.TLabel3.configure(relief=FLAT)
        self.TLabel3.configure(text='''Add user:''')

        self.TLabel15 = ttk.Label (self.TLabelframe5)
        self.TLabel15.place(relx=0.04,rely=0.64,height=19,width=83)
        self.TLabel15.configure(background=_bgcolor)
        self.TLabel15.configure(foreground="#000000")
        self.TLabel15.configure(relief=FLAT)
        self.TLabel15.configure(text='''User password:''')

        self.TEntry2 = ttk.Entry (self.TLabelframe5)
        self.TEntry2.place(relx=0.4,rely=0.35,relheight=0.16,relwidth=0.5)
        self.TEntry2.configure(takefocus="")
        self.TEntry2.configure(cursor="ibeam")

        self.TEntry3 = ttk.Entry (self.TLabelframe5)
        self.TEntry3.place(relx=0.4,rely=0.5,relheight=0.16,relwidth=0.5)
        self.TEntry3.configure(takefocus="")
        self.TEntry3.configure(cursor="ibeam")

        self.TEntry5 = ttk.Entry (self.TLabelframe5)
        self.TEntry5.place(relx=0.4,rely=0.64,relheight=0.16,relwidth=0.5)
        self.TEntry5.configure(takefocus="")
        self.TEntry5.configure(cursor="ibeam")

        self.TLabelframe6 = ttk.Labelframe (self.TNotebook1_pg0)
        self.TLabelframe6.place(relx=0.66,rely=0.02,relheight=0.53
                ,relwidth=0.33)
        self.TLabelframe6.configure(text='''System Settings''')
        self.TLabelframe6.configure(width=260)

        self.TLabel4 = ttk.Label (self.TLabelframe6)
        self.TLabel4.place(relx=0.04,rely=0.06,height=19,width=78)
        self.TLabel4.configure(background=_bgcolor)
        self.TLabel4.configure(foreground="#000000")
        self.TLabel4.configure(relief=FLAT)
        self.TLabel4.configure(text='''Stage3 tarball:''')

        self.TEntry4 = ttk.Entry (self.TLabelframe6)
        self.TEntry4.place(relx=0.5,rely=0.06,relheight=0.07,relwidth=0.48)
        self.TEntry4.configure(takefocus="")
        self.TEntry4.configure(cursor="ibeam")

        self.TLabel8 = ttk.Label (self.TLabelframe6)
        self.TLabel8.place(relx=0.04,rely=0.13,height=19,width=96)
        self.TLabel8.configure(background=_bgcolor)
        self.TLabel8.configure(foreground="#000000")
        self.TLabel8.configure(relief=FLAT)
        self.TLabel8.configure(text='''CPU architecture:''')

        self.TCombobox1 = ttk.Combobox (self.TLabelframe6)
        self.TCombobox1.place(relx=0.77,rely=0.13,relheight=0.07,relwidth=0.2)
        self.value_list = ['x86','AMD64',]
        self.TCombobox1.configure(values=self.value_list)
        self.TCombobox1.configure(textvariable=Installer_support.combobox)
        self.TCombobox1.configure(takefocus="")

        self.TLabel11 = ttk.Label (self.TLabelframe6)
        self.TLabel11.place(relx=0.04,rely=0.19,height=19,width=122)
        self.TLabel11.configure(background=_bgcolor)
        self.TLabel11.configure(foreground="#000000")
        self.TLabel11.configure(relief=FLAT)
        self.TLabel11.configure(text='''Number of CPU cores:''')

        self.TCombobox2 = ttk.Combobox (self.TLabelframe6)
        self.TCombobox2.place(relx=0.77,rely=0.19,relheight=0.07,relwidth=0.2)
        self.TCombobox2.configure(textvariable=Installer_support.combobox)
        self.TCombobox2.configure(takefocus="")

        self.TLabel12 = ttk.Label (self.TLabelframe6)
        self.TLabel12.place(relx=0.04,rely=0.26,height=19,width=96)
        self.TLabel12.configure(background=_bgcolor)
        self.TLabel12.configure(foreground="#000000")
        self.TLabel12.configure(relief=FLAT)
        self.TLabel12.configure(text='''Portage snapshot''')

        self.TLabel13 = ttk.Label (self.TLabelframe6)
        self.TLabel13.place(relx=0.08,rely=0.34,height=19,width=62)
        self.TLabel13.configure(background=_bgcolor)
        self.TLabel13.configure(foreground="#000000")
        self.TLabel13.configure(relief=FLAT)
        self.TLabel13.configure(text='''Bootloader''')

        self.TLabel20 = ttk.Label (self.TLabelframe6)
        self.TLabel20.place(relx=0.04,rely=0.57,height=19,width=59)
        self.TLabel20.configure(background=_bgcolor)
        self.TLabel20.configure(foreground="#000000")
        self.TLabel20.configure(relief=FLAT)
        self.TLabel20.configure(text='''Timezone:''')

        self.TLabel21 = ttk.Label (self.TLabelframe6)
        self.TLabel21.place(relx=0.04,rely=0.63,height=19,width=83)
        self.TLabel21.configure(background=_bgcolor)
        self.TLabel21.configure(foreground="#000000")
        self.TLabel21.configure(relief=FLAT)
        self.TLabel21.configure(text='''Kernel sources:''')

        self.TLabel22 = ttk.Label (self.TLabelframe6)
        self.TLabel22.place(relx=0.04,rely=0.7,height=19,width=91)
        self.TLabel22.configure(background=_bgcolor)
        self.TLabel22.configure(foreground="#000000")
        self.TLabel22.configure(relief=FLAT)
        self.TLabel22.configure(text='''Add RC services:''')

        self.TLabel23 = ttk.Label (self.TLabelframe6)
        self.TLabel23.place(relx=0.04,rely=0.77,height=19,width=102)
        self.TLabel23.configure(background=_bgcolor)
        self.TLabel23.configure(foreground="#000000")
        self.TLabel23.configure(relief=FLAT)
        self.TLabel23.configure(text='''Delete RC services:''')

        self.TCombobox3 = ttk.Combobox (self.TLabelframe6)
        self.TCombobox3.place(relx=0.35,rely=0.34,relheight=0.07,relwidth=0.28)
        self.value_list = ['Grub 2','Lilo','Grub (legacy)',]
        self.TCombobox3.configure(values=self.value_list)
        self.TCombobox3.configure(textvariable=Installer_support.combobox)
        self.TCombobox3.configure(takefocus="")

        self.TLabel1 = ttk.Label (self.TLabelframe6)
        self.TLabel1.place(relx=0.04,rely=0.5,height=19,width=62)
        self.TLabel1.configure(background=_bgcolor)
        self.TLabel1.configure(foreground="#000000")
        self.TLabel1.configure(relief=FLAT)
        self.TLabel1.configure(text='''Hostname:''')

        self.TEntry1 = ttk.Entry (self.TLabelframe6)
        self.TEntry1.place(relx=0.31,rely=0.5,relheight=0.07,relwidth=0.48)
        self.TEntry1.configure(takefocus="")
        self.TEntry1.configure(cursor="ibeam")

        self.TLabelframe1 = ttk.Labelframe (self.TNotebook1_pg2)
        self.TLabelframe1.place(relx=0.01,rely=0.02,relheight=0.44
                ,relwidth=0.96)
        self.TLabelframe1.configure(text='''Image using a Stage4 Recovery:''')
        self.TLabelframe1.configure(width=760)

        self.TLabel28 = ttk.Label (self.TLabelframe1)
        self.TLabel28.place(relx=0.01,rely=0.08,height=19,width=116)
        self.TLabel28.configure(background=_bgcolor)
        self.TLabel28.configure(foreground="#000000")
        self.TLabel28.configure(relief=FLAT)
        self.TLabel28.configure(text='''Select the Stage4 file:''')

        self.TButton3 = ttk.Button (self.TLabelframe1)
        self.TButton3.place(relx=0.88,rely=0.75,height=25,width=76)
        self.TButton3.configure(takefocus="")
        self.TButton3.configure(text='''Tbutton''')

        self.TProgressbar2 = ttk.Progressbar (self.TLabelframe1)
        self.TProgressbar2.place(relx=0.01,rely=0.63,relheight=0.09
                ,relwidth=0.96)

        self.TLabelframe2 = ttk.Labelframe (self.TNotebook1_pg2)
        self.TLabelframe2.place(relx=0.01,rely=0.46,relheight=0.47
                ,relwidth=0.96)
        self.TLabelframe2.configure(text='''Create Stage4 Recovery:''')
        self.TLabelframe2.configure(width=760)

        self.TLabel24 = ttk.Label (self.TLabelframe2)
        self.TLabel24.place(relx=0.01,rely=0.07,height=19,width=247)
        self.TLabel24.configure(background=_bgcolor)
        self.TLabel24.configure(foreground="#000000")
        self.TLabel24.configure(relief=FLAT)
        self.TLabel24.configure(text='''Select the destination of your Stage4 recovery:''')

        self.TButton4 = ttk.Button (self.TLabelframe2)
        self.TButton4.place(relx=0.88,rely=0.87,height=25,width=76)
        self.TButton4.configure(takefocus="")
        self.TButton4.configure(text='''Tbutton''')

        self.TProgressbar3 = ttk.Progressbar (self.TLabelframe2)
        self.TProgressbar3.place(relx=0.01,rely=0.76,relheight=0.08
                ,relwidth=0.96)





if __name__ == '__main__':
    vp_start_gui()



